apiVersion: apps/v1beta2
kind: Deployment
metadata:
  labels:
    k8s-app: authing-web
    qcloud-app: authing-web
  name: authing-web
  namespace: xauth
spec:
  selector:
    matchLabels:
      k8s-app: authing-web
      qcloud-app: authing-web
  template:
    metadata:
      labels:
        k8s-app: authing-web
        qcloud-app: authing-web
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: app.cluster.lucfish.com
                    operator: In
                    values:
                      - "1"
      containers:
        - env:
            - name: PATH
              value: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
            - name: NGINX_VERSION
              value: 1.17.1
            - name: NJS_VERSION
              value: 0.3.3
            - name: PKG_RELEASE
              value: 1~stretch
          image: ccr.ccs.tencentyun.com/mofanshow_services/authing-web:latest
          imagePullPolicy: Always
          name: authing-web
          resources:
            limits:
              cpu: 10m
              memory: 64Mi
            requests:
              cpu: 10m
              memory: 32Mi
      imagePullSecrets:
        - name: qcloudregistrykey
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: authing-web
  namespace: xauth
spec:
  ports:
    - name: web
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    k8s-app: authing-web
    qcloud-app: authing-web
  sessionAffinity: None
  type: ClusterIP
